### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by LeoAiolia** [gfaraday/g_faraday#1]
xcode 12.1, simulator iphone 12,
![1](https://user-images.githubusercontent.com/16910025/99020384-73536000-2599-11eb-8b65-e5a7fe387242.png)

**Comment by LeoAiolia** [comment]
flutter 1.22.3

**Comment by KevinGong2013** [comment]
fixed. 1db4d670602b3ed3e55bef4df40bbcd97481515e
