### ISSUE TITLE
有什么办法可以在object-c的工程里面使用？

### ISSUE THREAD

**Issue by wittech** [gfaraday/g_faraday#10]
有什么办法可以在object-c的工程里面使用？

**Comment by KevinGong2013** [comment]
从`g_faraday: 0.6.0-nullsafety.32`开始，已经支持在oc项目中使用了。

[objc Demo](https://github.com/gfaraday/g_faraday/tree/develop/example_objc_only)

这个issue我先关了，使用过程中有其他问题欢迎再开issue。
