### ISSUE TITLE
Android弹出页面的实现

### ISSUE THREAD

**Issue by ivoryxiong** [gfaraday/g_faraday#17]
请问`支持flutter作为弹出页面(背景透明到native层)` feature在Android上有实现吗？ 如实现了的话，有没有对应的example可以参考下，谢谢？

@KevinGong2013

**Comment by KevinGong2013** [comment]
https://github.com/gfaraday/g_faraday/blob/aa9b4bcdce7e10004f1617a1cbacc50f544bfaa1/example/android/app/src/main/kotlin/com/yuxiaor/flutter/g_faraday_example/basic/TransparentBackgroundFlutterActivity.kt#L1

看这里
