### ISSUE TITLE
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:     class io.flutter.embedding.android.XFlutterActivityAndFragmentDelegate, unresolved supertypes: ExclusiveAppComponent<Activity>

### ISSUE THREAD

**Issue by simaben** [gfaraday/g_faraday#3]
g_faraday: ^0.4.2
android端编译报错：
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.flutter.embedding.android.XFlutterActivityAndFragmentDelegate, unresolved supertypes: ExclusiveAppComponent<Activity>

**Comment by KevinGong2013** [comment]
建议使用 `g_faraday: ^0.5.0-nullsafety.4`  版本
