### ISSUE TITLE
请问一下与 Flutter Boost 的异同

### ISSUE THREAD

**Issue by airingursb** [gfaraday/g_faraday#4]
你好，我在调研业内的混合栈框架，发现了这款新出的框架。
想请教一下作者这款框架较 Flutter Boost 有什么新颖之处？

**Comment by KevinGong2013** [comment]
`g_faraday`不会为每一个新建的flutter页面创建一个对应的native容器。这是最核心的差异

`g_faraday`对混合开发中经常会遇到的问题也做了处理包括但不限于 页面之间传值，json处理，等等

具体你可以`clone`仓库，然后`cd Example && flutter run` 自己体验一下

**Comment by airingursb** [comment]
看了一下代码，内部是维护了一个 Navigator，所以跳 Flutter 页面的时候走的是 Navigator。

但是看了 README.md 的截图，说到其中 Flutter 跳 Flutter 走的新容器？那这张图片就不符合您说的 “不会为每一个新建的flutter页面创建一个对应的native容器” 了。

![image](https://user-images.githubusercontent.com/10513408/102180871-89c84080-3ee4-11eb-9b03-68e64f2d3e4b.png)

**Comment by KevinGong2013** [comment]
这个`case`主要是想表达`也支持`为每一个flutter页面新建一个native容器。(这样的话就和flutter_boost的逻辑一致了)

主要是为了方便从'flutter_boost'迁移。

**Comment by KevinGong2013** [comment]
我们之前大概有`10w+`行基于`flutter_boost`的代码，为了方便迁移到`g_faraday`最终还是保留了这个功能。

**Comment by airingursb** [comment]
了解了，感谢解答
