### ISSUE TITLE
Options可以从struct换成class吗

### ISSUE THREAD

**Issue by intspt** [gfaraday/g_faraday#9]
我们的项目是OC写的
使用FaradayNavigationDelegate的时候发现Options无法在桥接的头文件里生成对应的OC的表达

**Comment by KevinGong2013** [comment]
这个可以的， 但是我们没有针对oc做过测试。
你可以帮忙看看需要改动那些点，我们来试试陪一下

**Comment by KevinGong2013** [comment]
从`g_faraday: 0.6.0-nullsafety.32`开始，已经支持在oc项目中使用了。

[objc Demo](https://github.com/gfaraday/g_faraday/tree/develop/example_objc_only)

这个issue我先关了，使用过程中有其他问题欢迎再开issue。
